import random

class MySQLIndexSelector():

    def EnumerateHints(self, possible_keys, original_index_num=0):
        hints = []
        def EnumerateHintsRecursive(hint: str, depth, index_num = 0):
            # 最终的 index_num 应该在 [original_index_num - 1, original_index_num + 1] 之间
            if index_num > original_index_num + 1:
                return
            if index_num + (len(possible_keys) - depth) <= original_index_num - 1:
                return

            if depth == len(possible_keys):
                hints.append(hint)
                return
            table, index_list = possible_keys[depth]
            if len(index_list) == 0:
                EnumerateHintsRecursive(hint, depth + 1)
                return

            # EnumerateHintsRecursive(hint, depth + 1)
            EnumerateHintsRecursive(hint + f"NO_INDEX({table}) ", depth + 1, index_num)
            for index in index_list:
                EnumerateHintsRecursive(hint + f"INDEX({table} {index}) ", depth + 1, index_num + 1)

        EnumerateHintsRecursive("", 0)
        return hints

    def GenerateSQLsWithHints(self, sql, possible_keys, original_index_num = 0):
        sqls = []
        hints = self.EnumerateHints(list(possible_keys.items()), original_index_num)
        
        
        if len(hints) > 18:
            print(f"{len(hints)} sqls generated by index hints, random sample to 20")
            hints = random.sample(hints, 18)
        else:
            print(f"{len(hints) + 1} sqls generated by index hints")
        hints = [""] + hints + [""]
        
        for hint in hints:
            new_sql = self.CombineSqlWithHints(sql, hint)
            sqls.append(new_sql)
        
        return sqls, hints

    def CombineSqlWithHints(self, sql, hint):
        new_sql = sql.replace("SELECT ", f"SELECT /*+{hint}*/")
        return new_sql