import random

class MySQLHintsGenerator():

    def EnumerateIndexHints(self, possible_keys, original_index_num=0):
        hints = []
        def EnumerateIndexHintsRecursive(hint: str, depth, index_num = 0):
            # 最终的 index_num 应该在 [original_index_num - 1, original_index_num + 1] 之间
            if index_num > original_index_num + 1:
                return
            if index_num + (len(possible_keys) - depth) <= original_index_num - 1:
                return

            if depth == len(possible_keys):
                hints.append(hint)
                return
            table, index_list = possible_keys[depth]
            if len(index_list) == 0:
                EnumerateIndexHintsRecursive(hint, depth + 1)
                return

            # EnumerateIndexHintsRecursive(hint, depth + 1)
            EnumerateIndexHintsRecursive(hint + f"NO_INDEX({table}) ", depth + 1, index_num)
            for index in index_list:
                EnumerateIndexHintsRecursive(hint + f"INDEX({table} {index}) ", depth + 1, index_num + 1)

        EnumerateIndexHintsRecursive("", 0)
        return hints

    def EnumerateJoinPrefixHints(self, tables):
        hints = []
        hints.append("")
        for table in tables:
            hints.append(f"JOIN_PREFIX({table}) ")
        return hints

    def GenerateSQLsWithHints(self, sql, possible_keys, original_index_num = 0):
        sqls = []
        hints = []
        index_hints = self.EnumerateIndexHints(list(possible_keys.items()), original_index_num)
        # index_hints = [""]
        # prefix_hints = self.EnumerateJoinPrefixHints(list(possible_keys.keys()))
        prefix_hints = [""]

        for index_hint in index_hints:
            for prefix_hint in prefix_hints:
                hints.append(index_hint + prefix_hint)
        
        limitTo = 20

        if len(hints) > limitTo - 2:
            print(f"{len(hints)} sqls generated by index hints, random sample to {limitTo}")
            hints = random.sample(hints, limitTo - 2)
        else:
            print(f"{len(hints) + 1} sqls generated by index hints")
        hints = [""] + hints + [""]
        
        for hint in hints:
            new_sql = self.CombineSqlWithHints(sql, hint)
            sqls.append(new_sql)
        
        return sqls, hints

    def CombineSqlWithHints(self, sql, hint):
        new_sql = sql.replace("SELECT ", f"SELECT /*+{hint}*/")
        return new_sql