import random

class MySQLIndexSelector():

    def EnumerateHints(self, possible_keys):
        hints = []
        def EnumerateHintsRecursive(hint: str, depth):
            if depth == len(possible_keys):
                hints.append(hint)
                return
            table, index_list = possible_keys[depth]
            if len(index_list) == 0:
                EnumerateHintsRecursive(hint, depth + 1)
                return

            # EnumerateHintsRecursive(hint, depth + 1)
            EnumerateHintsRecursive(hint + f"NO_INDEX({table}) ", depth + 1)
            for index in index_list:
                EnumerateHintsRecursive(hint + f"INDEX({table} {index}) ", depth + 1)

        EnumerateHintsRecursive("", 0)
        return hints

    def GenerateSQLsWithHints(self, sql, possible_keys):
        sqls = []
        hints = self.EnumerateHints(list(possible_keys.items()))
        
        
        if len(hints) > 19:
            print(f"{len(hints)} sqls generated by index hints, random sample to 20")
            hints = random.sample(hints, 19)
        else:
            print(f"{len(hints) + 1} sqls generated by index hints")
        hints = [""] + hints
        
        for hint in hints:
            index = sql.find("SELECT")
            new_sql = sql[:index] + sql[index:].replace("SELECT ", f"SELECT /*+{hint}*/", 1)
            sqls.append(new_sql)
        
        return sqls, hints
